### ISSUE TITLE
Lighting - indicator for azimuth/altitude

### ISSUE THREAD

**Issue by chland** [llbit/chunky#487]
One thing I noticed after rendering a ton of pictures where i wanted to change the lighting is, that it is quite tedious to setup the lighting correctly.

One of the main problems I had is that I'm never 100% sure where the sun actually is in relation to my scene until i start rendering.

I was wondering if it would be possible to add a little widget to the lighting-screen. Basically a tiny render of a scene which uses the same camera angle as the real scene (so if you move your camera around, it would change accordingly). The scene itself would just be a sphere/box/... on a simple plane. Roughly something like this: https://unity3d.com/sites/default/files/realtime_0.png (ignore the light-indicator stuff - i'm only using this image because it shows the egg-thingy on a plane casting a shadow)

This way you could immediatly see how changing the azimuth or altitude of the sun would change the lighting of your scene. And rendering the preview shouldn't take that much time if its only 100*100 pixel or something like that.

**Comment by llbit** [comment]
@chland this is unrelated to this issue, but did you know we have a Discord for Chunky? Here's the invite link: https://discord.gg/VqcHpsF

You have been very active on the issue tracker: do you want to have contributor status so that you can assign labels to issues?

**Comment by jackjt8** [comment]
Current UI is as followed: ![image](https://user-images.githubusercontent.com/3740917/160241878-979655fc-81e1-4ed6-a45f-fdb47358eb46.png)

---

- [ ]  The `Sun azimuth` does not correctly follow conventions (NEW)
While it is correctly within -180<x<=180; Chunky:  North = 90, East = 0, South = -90, West = 180/-179.99.. Conventional: North = 0, East = 90, South = 180/-179.99.., West = -90. Not only we are dealing with a 90 degree rotation but we are doing so counter-clockwise. 

- [ ]  `Sun azimuth` North indication #487
Thankfully the `Sun azimuth` dial is correctly positionally aligned; Turning the dial to the top most position will place the sun to the North, etc. However no indication of North is given in both the controls and within the render preview. To address the controls we could simply need a North indicator. For the render preview this is more complex.

- [ ] `Sun altitude` shouldn't go +/-180; only +/-90 #487 #288
`Sun altitude` is... not good. It follows the same restrictions of `Sun azimuth` when in reality it would only need to be -90<x<=90. The solution here is a simple semi-circle as this would give us the range we need. The addition of a horizon, 0 degrees, indicator would further aid in usability. 

Below is an example of the Improved UI:
![Untitled](https://user-images.githubusercontent.com/3740917/160243096-52b4df74-240a-4e4f-8d07-27fada9a2851.png)


- [ ] North Indication within Map View (NEW)
This may not be required given it's typically assumed North is up... but it is a nice to have.


- [ ] Orientation indicator within Render Preview #487
This would be a significant improvement to user experience.

UE4 indicator 
![image](https://user-images.githubusercontent.com/3740917/160244338-8f99d143-f5d6-4033-9941-facd2e7ced51.png)

variation 
![image](https://user-images.githubusercontent.com/3740917/160244351-4f836add-cfdd-4732-abc7-70832175f21d.png)


- [ ] Sun direction indication within Render Preview #487
An argumentation of the orientation indicator could be made whereby an additional, free moving, line could show the sun orientation with respect to the scene axis.


- [ ] Display simulated sky colour (NEW)
The `Sun altitude` dial could be further improved by showing the average sky colour at this altitude. Currently the simulated sky colour depends on the sun position and there is no indication as to what to expect. This could be further expanded to include any night sky simulations when they become available. See [Minecraft clock](https://minecraft.fandom.com/wiki/Clock) just with a time of day gradients in addition to a night sky. Example with more realistic skies.. just as an average gradient and smoother ![image](https://user-images.githubusercontent.com/3740917/160244512-25247811-036d-4fa5-9fa8-cea716aebe94.png)
