### ISSUE TITLE
Minecraft 1.13 Checklist

### ISSUE THREAD

**Issue by llbit** [llbit/chunky#518]
Things to do for 1.13 (incomplete list):

- [x] Parse the new 1.13 block palettes.
- [ ] Loading all block types from tags.
- [ ] Support for new 1.13 block types.
- [ ] Add block palette to scene (json) file.
- [ ] Handle block palettes when loading 1.13 scenes.
- [ ] Make octree handling more robust to avoid index out of bounds problems when mixing up old/new octrees.
- [ ] Backward compatibility for pre-1.13.
- [ ] Bed texture is horizontally flipped (facing the bed).
- [ ] Wrong orientation in regular block textures.
- [ ] Wood blocks have orientation.
- [ ] Water filled blocks.
- [ ] Fire parts (individual flames).

**Comment by Vlad0Crystal** [comment]
Where is the promotion?

**Comment by llbit** [comment]
@Vlad0Crystal what promotion?

**Comment by Vlad0Crystal** [comment]
> @ Vlad0Crystal какое продвижение?

How soon will we wait for the update? 
Already released 1.14 ... and I'm still waiting. I need to remove unnecessary chunks. And it is not so convenient to do. How to influence the development?

**Comment by EmeraldSnorlax** [comment]
@Vlad0Crystal it's mostly developed by one person and llbit is trying his best. just be patient, it'll come eventually.

Hopefully when 1.13 is finished 1.14 should come out a lot faster and the block ID system has been totally BTFO'd for 1.13, so that's what's probably what's causing the long dev time

join the chunky discord to talk about chunky:

https://discord.gg/EUVduZj
